Add context/messaging to frequent rejection reasons
colorstackorg/oyster pull request #462
Opened 2024-08-19 20:43 UTC by arelymartinez16

## Description ✏️

Closes #216 

Key Features:

- Created a modal that shows when someone rejects an application and they can provide a reason why they're rejecting the application before rejecting
- Created "rejectionReason" column under the "applications" table in the database
- Rejection reason is shown on the UI in the "Rejected" and "All" views
- Include the rejection reason in the email template 

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [X] I have done a self-review of my code.
- [] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

2024-08-31 16:04 UTC, tomas-salgado requested changes
This is amazing work @arelymartinez16!! There were a lot of different parts to this issue but you handled it all really well-just tested it locally and it's working great! I left a few minor comments, but this should soon be good to go 🚀

2024-08-31 16:04 UTC, tomas-salgado commented on apps/admin-dashboard/app/routes/_dashboard.applications.tsx
> +    // Have to add a column of the rejection reason in the database
Let's remove these comments-looks like this is all done!

2024-08-31 16:04 UTC, tomas-salgado commented on packages/core/src/modules/application/application.core.ts
> +        // rejectionReason: reason || null,
remove this comment

2024-09-01 14:23 UTC, tomas-salgado commented on packages/db/src/migrations/20240819195536_add_rejection_reason_to_applications_table.ts
> +import { type Kysely } from 'kysely';
Note for @ramiAbdou: reminder to update the timestamp in file name

2024-09-12 01:34 UTC, tomas-salgado approved these changes
LGTM! Rami will take a final look and we'll ship it 🚢

2024-09-23 20:33 UTC, ramiAbdou approved these changes
Thanks for all the work here, @arelymartinez16! I made a couple tweaks to the UX that weren't in the original issue (mainly using a dropdown instead of a modal and some updated email copy).

I can't tell you how excited Jennifer (our community manager) is for these changes because we get so many emails asking why an application was rejected 😭

The impact of this will be huge! 🚀

2024-09-23 20:34 UTC, ramiAbdou commented on packages/email-templates/emails/application-rejected.tsx
> +
Updated!

2024-09-23 20:35 UTC, merged