feat: adds slack-user service 🚚
colorstackorg/oyster pull request #48
Opened 2024-03-30 05:16 UTC by omar-elbaz

## Description ✏️

Updates Slack User Service with two new functions. GetAllUsers and GetUserProfile

Related to #2 

- Implement two new functions in the slack-user.service file which call the slack api to:
- Get All Users in the ColorStack Family Workspace
- Fetch each user's individual User Profile

These will be needed in order to migrate birthdates from Slack to the ColorStack Member Profile Database, and will also be beneficial in the future when accessing Slack users.

Adjusted to implement our oyster RateLimiter to handle Slack Api's restrictions

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [ ] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

2024-03-31 18:38 UTC, ramiAbdou commented
@omar-elbaz please make sure to check all the relevant boxes in the checklist of the PR! It's always great practice to self-review your own PR so that first one will be mandatory! ✅ I'll update the documentation to make that a bit clearer.

2024-03-31 18:39 UTC, omar-elbaz commented
noted

2024-03-31 19:07 UTC, ramiAbdou requested changes
Great stuff, Omar! 🚀

I only have one concern with the approach. Currently, the plan is:
1. Get all the users in the Slack workspace.
2. Fetch each individual Slack profile.
3. Update the database based on the `slackId` of a student (I'm assuming).

The issue with that approach is there are a bunch of users in the Slack workspace that aren't associated with a member in our database (for various reasons), so we'd actually be hitting the Slack API more than we need to. Instead, we can:
1. Fetch all the `slackId`s from our database. This is one SQL query that is super quick and much more efficient than pulling ID's using the Slack API.
2. Fetch each individual Slack profile.
3. Update the database based on the `slackId` of a student.

The latter approach will ensure that we're not doing more work than we need to.

Let me know if you have any questions on that!

2024-03-31 19:16 UTC, omar-elbaz commented on packages/core/src/modules/slack/services/slack-user.service.ts
> +    } while (cursor);
No strong preference, this looks good. I will make the change.

2024-03-31 19:27 UTC, omar-elbaz commented on packages/core/src/modules/slack/services/slack-user.service.ts
> +import { Profile } from '@slack/web-api/dist/response/UsersProfileGetResponse';
I don't think that works. 
![image](https://github.com/colorstackorg/oyster/assets/114315316/65488994-ebba-4fad-95a6-0ad973e3988f)

2024-04-23 03:55 UTC, ramiAbdou commented
@omar-elbaz I'm going to close your PR and feel free to re-open once it's ready to be re-reviewed! I'm happy to chat through anything to drive any additional clarity as well.

2024-04-23 03:56 UTC, closed without merging