dev: test
colorstackorg/oyster pull request #500
Opened 2024-09-04 02:46 UTC by iperalta7

## Description ✏️

Closes #xxx

Describe what this PR does.

- Bullet points are helpful.
- Screenshots are helpful, if applicable.

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [ ] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

2024-09-05 01:41 UTC, iperalta7 commented
Tried to leave this more open for extension, since this is only a small start for chapters. Therefore, I mimicked more of how the school creation works with some core files in `@oyster/core`. I'd appreciate if this was the right track to go?

2024-09-21 21:30 UTC, tomas-salgado requested changes
Tested this locally and it's working great! Left a few minor comments-almost ready to go

2024-09-21 21:30 UTC, tomas-salgado commented on apps/admin-dashboard/app/shared/constants.ts
> +  '/schools/chapters/:id/create',
Let's make this 
`/schools/:id/chapter/create`
since we'll be taking the school id and then we'll create a chapter (rather than chapters)

2024-09-21 21:30 UTC, tomas-salgado commented on apps/admin-dashboard/app/routes/_dashboard.schools.chapters.$id.create.tsx
> +import {
Let's change the name of this file to '_dashboard.schools.$id.chapter.create.tsx'. See the other comment below

2024-09-21 21:30 UTC, tomas-salgado commented on apps/admin-dashboard/app/routes/_dashboard.schools.chapters.$id.create.tsx
> +  console.log('Loader school:', school);
Let's remove this log

2024-09-25 17:11 UTC, iperalta7 commented
@tomas-salgado should be all set now :) Thanks for the review! Ended up giving it a rebase to fixup my commit with your comments

2024-10-07 00:32 UTC, tomas-salgado approved these changes
Great work @iperalta7! LGTM 🚀

2025-02-25 19:26 UTC, ramiAbdou approved these changes

2025-02-25 19:28 UTC, merged