feat: notifications to write company reviews
colorstackorg/oyster pull request #556
Opened 2024-10-08 01:13 UTC by rafa1510

## Description ✏️

Closes #537 

Describe what this PR does.

- On a weekly basis, runs a job that fetches students that have a work experience that ended within the last week. Then, it has the Colorstack bot send a DM to these students encouraging them to leave a review of their experience.

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

2024-10-17 18:47 UTC, tomas-salgado requested changes
Nice work @rafa1510! Left a few comments-lmk when those are done and I'll take another look!

2024-10-17 18:47 UTC, tomas-salgado commented on packages/core/src/modules/member/member.worker.ts
> +        { name: 'student.company.review.notifications.weekly' },
let's change the name to be `student.company_review_notifications`. Make sure to also update in bull.types.ts

2024-10-17 18:47 UTC, tomas-salgado commented on packages/core/src/modules/employment/use-cases/send-company-review-notifications.ts
> + */
Let's update the function spec to reflect the change to making it a monthly job rather than weekly

2024-10-17 18:47 UTC, tomas-salgado commented on packages/core/src/modules/employment/use-cases/send-company-review-notifications.ts
> +    .where('endDate', 'is not', null)
Since `endDate` could be some time in the future, we also need to have a check to ensure `endDate` has already occurred.

2024-10-17 18:47 UTC, tomas-salgado commented on packages/core/src/modules/employment/use-cases/send-company-review-notifications.ts
> +  oneMonthAgo.setDate(oneMonthAgo.getDate() - 32);
We might have to think about this logic a bit. If we have this running every 32 days, couldn't it send notifications for 2 months? Potentially if this is scheduled correctly this isn't an issue, but it is something to think about to ensure the logic makes sense :)

2024-10-23 02:12 UTC, rafa1510 commented
hey @tomas-salgado, just pushed some changes, lmk if that works!

2024-10-27 19:46 UTC, tomas-salgado approved these changes
LGTM! Great work @rafa1510

2024-10-29 05:52 UTC, ramiAbdou approved these changes
Great work, @rafa1510!

I made a couple small changes [here](https://github.com/colorstackorg/oyster/pull/556/commits/81c71d962727171599bf0f2e90ceea7b8267532c) -- the most important of them being the join with the `companyReviews` table to ensure that there wasn't already a company review written for the work experience we wanted to send a notification for. Additionally, the URL we're now linking the member to is straight to the "add company review" form, instead of just the generic company page.

Thanks again for the contribution, I'm really hopeful that this notification is going to increase the # of company reviews we get by a lot!

Relatedly, I think another idea that's similar to this that could increase the # of company reviews we get is **right after a member adds a work experience (particularly from the past)**, imagine that we prompt them w/ a screen that says "would you like to add a company review"! Let me know if that interests you (cc: @tomas-salgado)!

2024-10-29 05:53 UTC, merged

2024-10-29 20:25 UTC, rafa1510 commented
Thanks @ramiAbdou! And yea I'm definitely down to work on adding a prompt after a member adds a work experience, @tomas-salgado could you make the issue?