feat: implement ai chat bot 🤖
colorstackorg/oyster pull request #588
Opened 2024-10-27 00:41 UTC by Boris713

## Description ✏️

Closes #541 

Describe what this PR does.

- Adds new tab/page for AI chat bot in member profiles
- Allows users to ask questions and have the ai answer them based off info from slack
<img width="1413" alt="Screenshot 2024-10-26 at 7 33 59 PM" src="https://github.com/user-attachments/assets/8589875f-732a-401b-aea9-6b8b9f149997">

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

## Areas of Interest 👀
- I want to ensure exporting of AnswerMemberProfileQuestion is done correctly. specifically using member-profile.server.ts
- Unable to test directly due to not having API credits. Although it should work, would be good to test.
- Order of icons in sidebar

2024-10-27 22:13 UTC, tomas-salgado requested changes
Great work @Boris713! The UI looks great. I wasn't able to test it fully because I don't have access to all of the embeddings for the Slack messages, but I'll ping Rami and he'll be able to help with this. 

Just left a couple of minor comments, after that this should be good for a final review

2024-10-27 22:13 UTC, tomas-salgado commented on apps/member-profile/app/routes/_profile.ai-chat-bot.tsx
> +                    'Ask me anything and Ill search the ColorStack Slack for you!'
typo: 'I'll' instead of Ill

2024-10-28 02:08 UTC, Boris713 commented
Fixed! can I get a LGTM?

2024-10-28 09:21 UTC, tomas-salgado approved these changes
LGTM!

2024-11-09 00:16 UTC, ramiAbdou approved these changes
Great work, @Boris713! 🚀

I made some updates and wanted to summarize them here:
- Since we're going to be rendering the response in the UI and not Slack, we needed to do some additional formatting of the Slack answer such that we can make the UI dynamic. For example, in order to render the "reference links" we need to parse the string into multiple "parts", when of them being a `reference` which our UI can now then work off of.
- The UI is updated such that it supports the above, and also it has a couple suggested prompts that the user can work off. We also now have a custom loading state since the response can take many seconds to come up.
- We'll cache the last question/answer that was asked for an hour so that the member doesn't lose it if they navigate away.

I'm going to follow up with some additional formatting for the sources that it retrieved the answer to as well. Take a look!

![Screenshot 2024-11-07 at 4 18 29 PM](https://github.com/user-attachments/assets/e54b43d2-00fe-4634-8040-bb2d7a398b38)

![Screenshot 2024-11-07 at 4 16 22 PM](https://github.com/user-attachments/assets/94da2670-89bf-45e9-abcc-e05ccde6bd6d)

2024-11-09 00:23 UTC, merged